Repository open-sauced/api, pull requests merged in 2023-08, with the labels that each got.

#230 feat: return all notifications even if they have been read
  src/user/entities/user-notification.entity.ts
  src/user/user-notifcation.service.ts
  src/user/user-notification.controller.ts
Labels: requested changes

#251 feat: generate blog summaries
  src/app.module.ts
  src/blogs/dtos/create-blog-summary.dto.ts
  src/blogs/issue-summary.controller.ts
  src/blogs/issue-summary.module.ts
  src/blogs/issue-summary.service.ts
Labels: awaiting review

#270 fix: Swagger API doc fixes for code generation
  src/auth/dtos/user-onboarding.dto.ts
  src/endorsement/endorsement.controller.ts
  src/main.ts
  src/user/dtos/create-user-highlight.dto.ts
  src/user/dtos/update-user-interests.dto.ts
  src/user/entities/user-highlight.entity.ts
  src/user/user.entity.ts
  swagger.yaml
Labels: ready-to-merge

#267 test: add unit test for user-collaboration service and controller
  src/user/user-collaboration.controller.spec.ts
  src/user/user-collaboration.service.spec.ts
Labels: ready-to-merge

#275 refactor: remove following users from top users when logged in user id is provided
  src/user/dtos/top-users.dto.ts
  src/user/services/user.service.ts
  swagger.yaml
Labels: awaiting review

#272 feat: add user organizations table migration and entity
  migrations/20230821112100_add_user_organizations.sql
  src/app.module.ts
  src/user/entities/user-organization.entity.ts
  src/user/user.entity.ts
  src/user/user.module.ts
Labels: ready-to-merge
